    create table category (
    id int4 generated by default as identity,
    name varchar(255),
    primary key (id));
    create table category_news (
    category_id int4 not null,
    news_id int4 not null);
    create table news1 (
    id int4 generated by default as identity,
     date timestamp,
     text varchar(2048),
     title varchar(255),
     category_id int4,
     primary key (id));
    alter table if exists category_news add constraint UK_kl47kx7y2l6w30omkd05g4pi3 unique (news_id);
    alter table if exists category_news add constraint FK81ohn8c9c3rke509tfkhd39pm foreign key (news_id) references news1;
    alter table if exists category_news add constraint FK8xdyh5ql3heux0wdx4u2t26ut foreign key (category_id) references category;
    alter table if exists news1 add constraint FKg6evl83nesjw09h1lmupunf6 foreign key (category_id) references category;